export const registry = {
    Gender: () => import('./schemes/rivm/gender.ts'),
    GenderAlt: () => import('./schemes/rivm/genderAlt.ts'),
    Standard: () => import('./schemes/rivm/standard.ts'),

    BrBG: () => import('./schemes/colorbrewer/diverging/BrBG.ts'),
    PiYG: () => import('./schemes/colorbrewer/diverging/PiYG.ts'),
    PRGn: () => import('./schemes/colorbrewer/diverging/PRGn.ts'),
    PuOr: () => import('./schemes/colorbrewer/diverging/PuOr.ts'),
    RdBu: () => import('./schemes/colorbrewer/diverging/RdBu.ts'),
    RdGy: () => import('./schemes/colorbrewer/diverging/RdGy.ts'),
    RdYlBu: () => import('./schemes/colorbrewer/diverging/RdYlBu.ts'),
    RdYlGn: () => import('./schemes/colorbrewer/diverging/RdYlGn.ts'),
    Spectral: () => import('./schemes/colorbrewer/diverging/Spectral.ts'),

    Accent: () => import('./schemes/colorbrewer/qualitative/Accent.ts'),
    Dark2: () => import('./schemes/colorbrewer/qualitative/Dark2.ts'),
    Paired: () => import('./schemes/colorbrewer/qualitative/Paired.ts'),
    Pastel1: () => import('./schemes/colorbrewer/qualitative/Pastel1.ts'),
    Pastel2: () => import('./schemes/colorbrewer/qualitative/Pastel2.ts'),
    Set1: () => import('./schemes/colorbrewer/qualitative/Set1.ts'),
    Set2: () => import('./schemes/colorbrewer/qualitative/Set2.ts'),
    Set3: () => import('./schemes/colorbrewer/qualitative/Set3.ts'),

    Blues: () => import('./schemes/colorbrewer/sequential/Blues.ts'),
    BuGn: () => import('./schemes/colorbrewer/sequential/BuGn.ts'),
    BuPu: () => import('./schemes/colorbrewer/sequential/BuPu.ts'),
    GnBu: () => import('./schemes/colorbrewer/sequential/GnBu.ts'),
    Greens: () => import('./schemes/colorbrewer/sequential/Greens.ts'),
    Greys: () => import('./schemes/colorbrewer/sequential/Greys.ts'),
    Oranges: () => import('./schemes/colorbrewer/sequential/Oranges.ts'),
    OrRd: () => import('./schemes/colorbrewer/sequential/OrRd.ts'),
    PuBu: () => import('./schemes/colorbrewer/sequential/PuBu.ts'),
    PuBuGn: () => import('./schemes/colorbrewer/sequential/PuBuGn.ts'),
    PuRd: () => import('./schemes/colorbrewer/sequential/PuRd.ts'),
    Purples: () => import('./schemes/colorbrewer/sequential/Purples.ts'),
    RdPu: () => import('./schemes/colorbrewer/sequential/RdPu.ts'),
    Reds: () => import('./schemes/colorbrewer/sequential/Reds.ts'),
    YlGn: () => import('./schemes/colorbrewer/sequential/YlGn.ts'),
    YlGnBu: () => import('./schemes/colorbrewer/sequential/YlGnBu.ts'),
    YlOrBr: () => import('./schemes/colorbrewer/sequential/YlOrBr.ts'),
    YlOrRd: () => import('./schemes/colorbrewer/sequential/YlOrRd.ts'),
};
